完善错误处理宏，打印报错代码所在文件及行数等具体信息
PanZezhong1725/operators pull request #120
Opened 2024-11-22 09:01 UTC by kilinchange

2024-11-26 05:11 UTC, Ziminli requested changes

2024-11-26 05:11 UTC, Ziminli commented on operatorspy/tests/conv.py
> +        # test(lib, handle, "cpu", x_shape, w_shape, pads, strides, dilations, x_strides, tensor_dtype=torch.float16)
FP16的测试是不是意外注释掉了？

2024-11-26 05:45 UTC, PanZezhong1725 commented on operatorspy/tests/conv.py
> +        # test(lib, handle, "cpu", x_shape, w_shape, pads, strides, dilations, x_strides, tensor_dtype=torch.float16)
我还以为是刻意这么做的

2024-11-26 05:50 UTC, kilinchange commented on operatorspy/tests/conv.py
> +        # test(lib, handle, "cpu", x_shape, w_shape, pads, strides, dilations, x_strides, tensor_dtype=torch.float16)
是误删了...因为我本地 pytorch 跑不了 fp16 的测例，临时注释了下

2024-11-26 06:01 UTC, kilinchange commented on operatorspy/tests/conv.py
> +        # test(lib, handle, "cpu", x_shape, w_shape, pads, strides, dilations, x_strides, tensor_dtype=torch.float16)
fixed

2024-11-26 06:36 UTC, Ziminli approved these changes

2024-11-28 08:01 UTC, PanZezhong1725 approved these changes

2024-11-28 08:01 UTC, merged