Refactor：算子库重构
PanZezhong1725/operators pull request #33
Opened 2024-08-20 02:51 UTC by PanZezhong1725

2024-08-21 03:25 UTC, PanZezhong1725 commented on include/ops/causal_softmax/causal_softmax.h
> +// @deprecated
将作废的函数和文件标记

2024-08-22 09:44 UTC, kilinchange commented on src/devices/handle.cc
> +            delete (infiniopHandle_t) handle;
传进来的不是已经是 infiniopHandle_t 了，为什么这里还要强转？

2024-08-22 10:13 UTC, kilinchange requested changes

2024-08-22 10:13 UTC, kilinchange commented on src/ops/utils.h
> +    } pun;
pun 是什么的缩写？

2024-08-23 01:48 UTC, PanZezhong1725 commented on src/devices/handle.cc
> +            delete (infiniopHandle_t) handle;
要强转成各自硬件的handle，我写错了

2024-08-23 01:50 UTC, PanZezhong1725 commented on src/ops/utils.h
> +    } pun;
双关

2024-08-23 02:04 UTC, kilinchange approved these changes

2024-08-23 02:10 UTC, merged