Refactor swiglu cpu&cuda
PanZezhong1725/operators pull request #37
Opened 2024-08-27 09:17 UTC by kilinchange

重构 swiglu cpu&cuda 算子

2024-08-27 09:19 UTC, kilinchange commented
![image](https://github.com/user-attachments/assets/f4374a63-0567-4a76-bcc7-a77483902378)

2024-08-28 09:44 UTC, PanZezhong1725 requested changes

2024-08-28 09:44 UTC, PanZezhong1725 commented on src/ops/swiglu/cuda/swiglu_cuda.cc
> +    if (c_desc->ndim != 2 || a_desc->ndim != 2 || b_desc->ndim != 2) {
如果只支持两维请在文档中说明。第二维如果必须连续请检查，并在文档中说明。

2024-08-28 09:44 UTC, PanZezhong1725 commented on src/ops/swiglu/cpu/swiglu_cpu.cc
> +    if (c_desc->ndim != 2 || a_desc->ndim != 2 || b_desc->ndim != 2) {
如果只支持两维请在文档中说明。第二维如果必须连续请检查，并在文档中说明。

2024-08-29 02:25 UTC, kilinchange commented on src/ops/swiglu/cuda/swiglu_cuda.cc
> +    if (c_desc->ndim != 2 || a_desc->ndim != 2 || b_desc->ndim != 2) {
文档已补充，连续性检查代码中已添加。

2024-08-29 02:25 UTC, kilinchange commented on src/ops/swiglu/cpu/swiglu_cpu.cc
> +    if (c_desc->ndim != 2 || a_desc->ndim != 2 || b_desc->ndim != 2) {
文档已补充，连续性检查代码中已添加。

2024-08-29 02:37 UTC, PanZezhong1725 approved these changes

2024-08-29 02:37 UTC, merged