重构rearrange的cpu/cuda算子
PanZezhong1725/operators pull request #39
Opened 2024-08-29 02:14 UTC by bitzyz

重构rearrange的cpu/cuda算子

2024-08-29 06:52 UTC, PanZezhong1725 requested changes

2024-09-02 01:16 UTC, bitzyz commented on operatorspy/tests/rearrange.py
> +        f"Testing CausalSoftmax on {torch_device} with x_shape:{x_shape} x_stride:{x_stride} y_shape:{y_shape} y_stride:{y_stride} x_dtype:{x_dtype}"
已修复

2024-09-02 01:16 UTC, bitzyz commented on operatorspy/tests/rearrange.py
> +    # if args.bang:
已修复

2024-09-02 01:17 UTC, bitzyz commented on src/ops/rearrange/cpu/rearrange_cpu.cc
> +    if (dst->ndim != src->ndim || dst->ndim < 2) {
已修改文档

2024-09-02 01:17 UTC, bitzyz commented on src/ops/rearrange/cuda/rearrange.cu
> +}
已修复

2024-09-02 01:17 UTC, bitzyz commented on src/ops/rearrange/cuda/rearrange.cc
> +        csa = dst->strides[ndim - 2] / dst->dt.size;
已修复

2024-09-05 06:29 UTC, zhangyue207 approved these changes

2024-09-11 06:07 UTC, PanZezhong1725 approved these changes

2024-09-11 06:08 UTC, merged