swiglu：重构寒武纪平台手写bangC算子swiglu
PanZezhong1725/operators pull request #40
Opened 2024-08-30 03:11 UTC by xgqdut2016

2024-09-06 07:38 UTC, kilinchange requested changes

2024-09-06 07:38 UTC, kilinchange commented on src/ops/swiglu/bang/swiglu_bang.mlu
>      // cnrtQueueSync(queue);
这行 sync 注释是不是可以删了

2024-09-06 07:38 UTC, kilinchange commented on src/ops/swiglu/bang/swiglu_bang.mlu
> +    if (dtype_eq(desc->dtype, F16)) {
需要在调用核函数之前 set deviceId，参考 https://github.com/PanZezhong1725/operators/pull/43

2024-09-06 07:42 UTC, kilinchange commented
麻烦贴一下测试通过的截图

2024-09-06 08:25 UTC, xgqdut2016 commented
![微信截图_20240906162340](https://github.com/user-attachments/assets/a48a864b-ab81-4131-b875-5c6a4a4e91cf)

2024-09-10 08:49 UTC, kilinchange requested changes

2024-09-10 08:49 UTC, kilinchange commented on src/ops/swiglu/bang/swiglu_bang.h
> +                            void *a,
只读的地址麻烦写成 const void*

2024-09-10 08:49 UTC, kilinchange commented on src/ops/swiglu/bang/swiglu_bang.mlu
> +void swiglu_bang_f16(SwiGLUBangDescriptor_t desc, void *a, void *b, void *c, void *stream) {
只读地址麻烦写成 const void*

2024-09-10 08:49 UTC, kilinchange commented on src/ops/swiglu/bang/swiglu_bang.mlu
> +                           void *stream){
只读地址

2024-09-11 07:20 UTC, kilinchange requested changes

2024-09-11 07:20 UTC, kilinchange commented on operatorspy/tests/swiglu.py
> +    #return a * torch.nn.functional.silu(b.float()).to(b.dtype)
这个注释删了吧

2024-09-11 08:36 UTC, kilinchange approved these changes

2024-09-14 04:23 UTC, merged