refactored Add operator and fixed f16 and f32 conversion functions
PanZezhong1725/operators pull request #41
Opened 2024-08-30 03:39 UTC by Ziminli

- fixed f16 and f32 conversion functions
 - added the CPU and CUDA implementation of Add operator
 - added the fronted test for the Add operator

2024-08-30 06:59 UTC, PanZezhong1725 requested changes

2024-08-30 06:59 UTC, PanZezhong1725 commented on src/ops/add/cuda/add.cuh
> +    cudnnHandle_t handle;
把cudnn handle放到infiniopHandle里去

2024-08-30 06:59 UTC, PanZezhong1725 commented on src/ops/add/cuda/add.cuh
> +infiniopStatus_t cudaAdd(AddCudaDescriptor_t desc,
为什么接口要传workspace，这里都没有提供get workspace接口

2024-08-30 06:59 UTC, PanZezhong1725 commented on src/devices/cpu/common_cpu.cc
> +}
文件结尾加空行

2024-08-30 06:59 UTC, PanZezhong1725 commented on src/ops/add/cuda/add.cu
> +    checkCudnnError(cudnnCreateTensorDescriptor(&tensorDesc));
所有和具体计算无关的操作全都放到create descriptor里， 包括tensor descriptor，op之类的

2024-08-30 06:59 UTC, PanZezhong1725 commented on src/devices/cuda/common_cuda.h
> +    throw std::runtime_error(std::string("[") + __FILE__ + ":" +           \
库函数检查不要报错，返回相应的error code

2024-08-30 06:59 UTC, PanZezhong1725 commented on src/ops/add/cuda/add.cc
> +    if (!dtype_eq(c->dt, F16) || !dtype_eq(a->dt, F16) || !dtype_eq(b->dt, F16)) {
以后肯定要支持不同的数据类型，可以先检查类型，再检查所有tensor类型是否一致

2024-08-30 06:59 UTC, PanZezhong1725 commented on src/ops/add/cpu/add_cpu.cc
> +    uint64_t data_size = std::accumulate(a->shape, a->shape + ndim, 1ULL, std::multiplies<uint64_t>());
这么乘是要求张量覆盖的内存必须没有间隙的意思吗

2024-08-30 08:08 UTC, Ziminli commented on src/ops/add/cpu/add_cpu.cc
> +    uint64_t data_size = std::accumulate(a->shape, a->shape + ndim, 1ULL, std::multiplies<uint64_t>());
这个是默认shape的数据是连续的。这个可能不连续吗？

2024-08-30 08:48 UTC, PanZezhong1725 commented on src/ops/add/cpu/add_cpu.cc
> +    uint64_t data_size = std::accumulate(a->shape, a->shape + ndim, 1ULL, std::multiplies<uint64_t>());
我不知道啊，如果你要求连续，就要做检查，然后文档上写清楚

2024-09-02 08:02 UTC, Ziminli commented on src/ops/add/cpu/add_cpu.cc
> +    uint64_t data_size = std::accumulate(a->shape, a->shape + ndim, 1ULL, std::multiplies<uint64_t>());
这个是默认这个
<img width="338" alt="image" src="https://github.com/user-attachments/assets/83535cc6-22a6-489a-a719-edf71654a26e">
shape的数据是连续的，张量数据我在文档上细化了要求，代码做了检查

2024-09-06 07:13 UTC, kilinchange requested changes

2024-09-06 07:13 UTC, kilinchange commented on src/ops/add/cuda/add.cc
> +            return STATUS_BAD_TENSOR_SHAPE;
不一定形状完全一样，根据 onnx 文档描述，add 需要支持双向广播

2024-09-06 07:13 UTC, kilinchange commented on src/ops/add/cuda/add.cuh
> +                                         int device_id);
同样，device_id 从 handle 里拿，不用单独传

2024-09-06 07:42 UTC, kilinchange commented
麻烦贴一下测试通过的截图

2024-09-11 02:52 UTC, Ziminli commented on src/devices/cuda/common_cuda.h
> +#include <string>
是的，历史遗留问题

2024-09-11 07:30 UTC, Ziminli commented on src/ops/add/cuda/add.cc
> +    const float beta = 0.0f;
<img width="588" alt="image" src="https://github.com/user-attachments/assets/2e1038c5-ca05-4c6a-b417-4e4793b89628">
alpha和beta是用在这里加权加法之类的情况下，我看infiniTensor里好像是直接写死默认为正常加法了，如果我们需要的话也可以让用户传入？

2024-09-20 09:29 UTC, Ziminli commented
<img width="829" alt="image" src="https://github.com/user-attachments/assets/e5922c59-03c2-4803-9231-e6894b7ae7fb">

2024-09-23 02:45 UTC, kilinchange requested changes

2024-09-23 02:45 UTC, kilinchange commented on operatorspy/tests/test_utils.py
> +class Inplace(Enum):
这个类放这个文件里好像不太合适，因为别的算子可能不是这几种 inplace 情况，建议放到 add.py 里

2024-09-23 02:46 UTC, kilinchange commented
另外 ci 没过，麻烦看下是什么情况

2024-09-23 04:42 UTC, kilinchange approved these changes

2024-09-24 02:52 UTC, PanZezhong1725 approved these changes

2024-09-24 02:52 UTC, merged