Ascend
PanZezhong1725/operators pull request #42
Opened 2024-09-02 03:38 UTC by zhangyue207

2024-09-25 02:54 UTC, xgqdut2016 commented on src/ops/causal_softmax/ascend/causal_softmax_aclnn.h
> +    AscendHandle_t handle;
创建descriptor的时候需要加一个成员变量device_id吧

2024-09-25 03:26 UTC, xgqdut2016 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +                              void *y,
这里的x,w都得设置const吧

2024-09-25 03:36 UTC, xgqdut2016 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.h
> +    double epsilon;
上面创建descriptor的时候eps是float类型，这里怎么变成了double

2024-09-25 03:38 UTC, xgqdut2016 commented on src/ops/rotary_embedding/ascend/rotary_embedding.cc
> +                               int32_t nt, int32_t nh, int32_t dh,
这里的pos,sin,cos是不是都要有const关键字

2024-10-14 09:09 UTC, kilinchange requested changes

2024-10-14 09:09 UTC, kilinchange commented on src/ops/rotary_embedding/cpu/rotary_embedding_cpu.cc
> +    //     return STATUS_BAD_TENSOR_DTYPE;
这个注释需要恢复

2024-10-14 09:09 UTC, kilinchange commented on src/ops/swiglu/ascend/swiglu.cc
> +// void swiglu_aclnn_f16(SwigluAscendCDescriptor *descriptor, Tensor gate,
这一块注释代码需要吗？不需要了的话删了吧

2024-10-14 09:09 UTC, kilinchange commented on src/ops/swiglu/operator.cc
> +// #include "ascend/swiglu.h"
不需要的注释可以删了

2024-10-14 09:09 UTC, kilinchange commented on src/ops/swiglu/operator.cc
> +            // return ascendCreateSwiGLUDescriptor(handle, (SwiGLUAscendDescriptor_t *) desc_ptr, c_desc, a_desc, b_desc);
不需要的注释可以删了

2024-10-14 09:09 UTC, kilinchange commented on src/ops/swiglu/operator.cc
> +            // return ascendSwiGLU((SwiGLUAscendDescriptor_t) desc, c, a, b, stream);
不需要的注释可以删了

2024-10-14 09:09 UTC, kilinchange commented on src/ops/swiglu/operator.cc
> +            // return ascendDestroySwiGLUDescriptor((SwiGLUAscendDescriptor_t) desc);
不需要的注释可以删了

2024-10-14 09:09 UTC, kilinchange commented on src/ops/matmul/ascend/matmul_aclnn.cc
> +                  //     aclnnBatchMatMulGetWorkspaceSize(ta, tb, tc, desc->mt, &workspaceSize, executor);
不需要的注释可以删了

2024-10-14 09:09 UTC, kilinchange commented on src/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
> +    // float neg_inf = -100000000;
不需要的注释可以删了

2024-10-15 01:52 UTC, kilinchange requested changes

2024-10-15 01:52 UTC, kilinchange commented on operatorspy/utils.py
> +    # new_tensor.set_(new_tensor.storage(), offset, shape, tuple(new_strides))
不需要的注释可以删了

2024-10-15 01:52 UTC, kilinchange commented on src/devices/ascend/ascend_handle.cc
> +    pool->push(std::move(executor));
executor 在用到的时候创建即可，不需要用 pool

2024-11-13 07:34 UTC, PanZezhong1725 commented
All feature merged in other PRs. Close.

2024-11-13 07:34 UTC, closed without merging