Refactor: 重构RoPE算子（CPU、CUDA）
PanZezhong1725/operators pull request #48
Opened 2024-09-11 02:41 UTC by PanZezhong1725

2024-09-12 03:21 UTC, zhangyue207 approved these changes
没有看 .cu 部分，其他都看过

2024-09-12 03:21 UTC, zhangyue207 approved these changes

2024-09-12 05:50 UTC, kilinchange requested changes

2024-09-14 01:43 UTC, PanZezhong1725 commented on src/ops/rotary_embedding/cuda/rotary_embedding.cu
> +         stride1 = desc->strides[1] / 2;
因为要每两个打包为half2

2024-09-14 02:26 UTC, PanZezhong1725 commented on src/ops/rotary_embedding/cuda/rotary_embedding.cc
> +    return STATUS_SUCCESS;
已改

2024-09-14 02:26 UTC, PanZezhong1725 commented on operatorspy/tests/rotary_embedding.py
已添加

2024-09-18 02:32 UTC, kilinchange approved these changes

2024-09-18 03:08 UTC, merged