bang_rearrange：重构rearrange的寒武纪接口
PanZezhong1725/operators pull request #55
Opened 2024-09-12 07:01 UTC by xgqdut2016

2024-09-12 07:01 UTC, xgqdut2016 commented
<img width="749" alt="1726124504664" src="https://github.com/user-attachments/assets/193cb485-3a04-41f3-a3d3-c09341661363">

2024-09-18 03:54 UTC, bitzyz requested changes

2024-09-18 03:54 UTC, bitzyz commented on src/ops/matmul/bang/matmul_cnnl.cc
> +    // auto info = MatmulInfo(c, a, b, false);
这块是在做什么

2024-09-18 03:54 UTC, bitzyz commented on src/ops/rearrange/operator.cc
> +//#include "bang/rearrange_cnnl.h"
这句注释是否还有用？

2024-09-18 03:54 UTC, bitzyz commented on src/ops/rearrange/bang/rearrange_bang.mlu
> +    if (dtype_eq(desc->dtype, F16)) {
为啥会有这种限制？

2024-09-18 03:54 UTC, bitzyz commented on src/ops/rearrange/bang/rearrange_bang.h
> +    uint64_t *mlu_shape_dst, *mlu_shape_src;
我理解src和dst的shape是一样的吧，是不是只要一个就行

2024-09-19 02:17 UTC, xgqdut2016 commented on src/ops/matmul/bang/matmul_cnnl.cc
> +    // auto info = MatmulInfo(c, a, b, false);
这是因为matmul那部分内容一直有问题，据晨婕说那部分matmul还需要重新实现，因此先把这部分内容全部注释掉了

2024-09-19 02:18 UTC, xgqdut2016 commented on src/ops/matmul/bang/matmul_cnnl.cc
> +    // auto info = MatmulInfo(c, a, b, false);
> 这块是在做什么

这是因为matmul那部分内容一直有问题，据晨婕说那部分matmul还需要重新实现，因此先把这部分内容全部注释掉了

2024-09-19 02:19 UTC, xgqdut2016 commented on src/ops/rearrange/operator.cc
> +//#include "bang/rearrange_cnnl.h"
> 这句注释是否还有用？
之后如果需要调库，到时候就需要这个头文件，这里先注释掉

2024-09-19 02:21 UTC, xgqdut2016 commented on src/ops/rearrange/bang/rearrange_bang.h
> +    uint64_t *mlu_shape_dst, *mlu_shape_src;
的确是如此，但是我看见CPU这边也是分配了两个shape，一个shape_dst，一个shape_src，所以我自己在MLU上也是如法炮制

2024-09-23 07:15 UTC, bitzyz commented on src/ops/rearrange/bang/rearrange_bang.h
> +    uint64_t *mlu_shape_dst, *mlu_shape_src;
其实cpu确实也不该写，不过cpu不需要分配内存和数据搬运吧，mlu应该用，不过估计也不会影响太大的性能，抉择一下用不用改吧

2024-09-23 09:22 UTC, closed without merging