[WIP] 添加 mlp 融合算子
PanZezhong1725/operators pull request #60
Opened 2024-09-20 09:27 UTC by kilinchange

2024-09-24 08:58 UTC, kilinchange commented
![image](https://github.com/user-attachments/assets/6f4e796a-b947-401b-a5a6-7c4260ee6e41)
cpu 和 cuda 均通过

2024-10-16 05:51 UTC, PanZezhong1725 requested changes

2024-10-16 05:51 UTC, PanZezhong1725 commented on include/ops/mlp/mlp.h
> +                                          void *w12,
不会被修改的输入加上const

2024-10-16 05:59 UTC, kilinchange commented on include/ops/mlp/mlp.h
> +                                          void *w12,
fixed

2024-10-16 07:23 UTC, PanZezhong1725 approved these changes

2024-10-16 07:23 UTC, merged