Add conv
PanZezhong1725/operators pull request #61
Opened 2024-09-23 08:37 UTC by Ziminli

- Add Conv CPU and CUDA implementation and its frontend test

2024-10-25 07:41 UTC, kilinchange requested changes

2024-10-25 07:41 UTC, kilinchange commented on src/ops/conv/cuda/conv.cc
> +                                          int device_id) {
device_id 从 handle 里获取就行，不用单独传参

2024-10-25 07:41 UTC, kilinchange commented on include/ops/conv/conv.h
> +                                                           int device_id);
device_id 参数不需要

2024-10-25 07:41 UTC, kilinchange commented on src/ops/conv/cpu/conv_cpu.cc
> +}
文件结尾需要空行

2024-11-01 02:24 UTC, kilinchange requested changes

2024-11-01 02:24 UTC, kilinchange commented on src/ops/conv/cuda/conv.cc
> +                return CUDNN_DATA_FLOAT;
为什么 half/bf16/float 返回的都是 CUDNN_DATA_FLOAT 呢？

2024-11-01 02:24 UTC, kilinchange commented on src/ops/conv/cuda/conv.cu
> +    checkCudnnError(use_cudnn(desc->cudnn_handles_t, desc->device_id,
use_cudnn 函数里应当用 cudnnSetStream() 设置 stream，参考 use_cublas

2024-11-05 05:44 UTC, PanZezhong1725 approved these changes

2024-11-05 06:00 UTC, kilinchange approved these changes

2024-11-05 06:12 UTC, PanZezhong1725 requested changes

2024-11-05 06:12 UTC, PanZezhong1725 commented on src/ops/conv/cpu/conv_cpu.cc
> +#pragma omp parallel for
omp for不要用nested，可以用collapse

2024-11-05 07:24 UTC, PanZezhong1725 approved these changes

2024-11-05 07:24 UTC, merged

2024-11-06 02:22 UTC, kilinchange approved these changes