Add ReLU CPU and CUDA implementation
PanZezhong1725/operators pull request #68
Opened 2024-09-24 08:00 UTC by Ziminli

- Added ReLU CPU and CUDA implementation and its frontend test

2024-10-24 06:30 UTC, Ziminli commented
fp16:
<img width="544" alt="image" src="https://github.com/user-attachments/assets/4bfe5429-7661-4201-b7e1-5cca36c8a0ed">
fp32:
<img width="545" alt="image" src="https://github.com/user-attachments/assets/07ac4c12-b284-4ae9-9cbe-fe30504d2b40">

2024-10-24 08:58 UTC, kilinchange commented
新添加的 op 要在 include/infini_operators.h 里加一下头文件

2024-10-25 02:52 UTC, kilinchange commented on src/ops/relu/cuda/relu.cu
> + * @tparam TComp - The computation data type used for arithmetic operations.
T 数据类型的大小和 TComp 的大小有要求吗？需要 T 更大吗？

2024-10-25 02:52 UTC, kilinchange commented on src/ops/relu/cuda/relu.cu
> +        return false;
这里为什么只返回 false？

2024-10-25 04:34 UTC, Ziminli commented on src/ops/relu/cuda/relu.cu
> + * @tparam TComp - The computation data type used for arithmetic operations.
需要，已注明

2024-10-25 04:43 UTC, Ziminli commented on src/ops/relu/cuda/relu.cu
> +        return false;
因为vecN的赋值过程中是必须要进行比较的，所以实际的比较部分在赋值的过程中进行，小于号无需做额外的比较。但relu里保留比较的格式是为了让基础数据类型也可以正确进行relu操作，同时也是为了明确正确的relu逻辑。

2024-10-25 06:23 UTC, kilinchange approved these changes

2024-11-04 06:07 UTC, PanZezhong1725 requested changes

2024-11-04 06:07 UTC, PanZezhong1725 commented on src/ops/relu/cuda/relu.cc
> +    cudaDeviceProp prop;
把这部分放到公共的cuda代码里吧，建handle的时候，把这些信息拿到存handle里

2024-11-06 02:08 UTC, PanZezhong1725 approved these changes

2024-11-06 02:08 UTC, merged