Dev ascend softmax
PanZezhong1725/operators pull request #81
Opened 2024-10-17 09:07 UTC by zhangyue207

拆分 ascend 分支 softmax 实现，删除了 AscendContext 中涉及的handle 池，改写在 opDescriptor中，因为昇腾的exectuor 是算子独享的

2024-10-17 12:15 UTC, kilinchange requested changes

2024-10-17 12:15 UTC, kilinchange commented on src/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
> +    int64_t total_seq_len = static_cast<int64_t>(shape[ndim - 1]);
是不是应该先检查一下 2 <= ndim < 4（文档里写的是最多三个维度）

2024-10-17 12:15 UTC, kilinchange commented on src/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
> +                workspace_size * ele_size,
workspace_size 单位就是字节，为什么还要乘以 ele_size？

2024-10-18 01:49 UTC, zhangyue207 commented on operatorspy/tests/causal_softmax.py
> +    ans = causal_softmax(x)
之前解释过，先计算后更改stride ， 昇腾pytorch 会报错

2024-10-18 01:58 UTC, zhangyue207 commented on src/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
> +                workspace_size * ele_size,
确实

2024-10-18 01:58 UTC, zhangyue207 commented on src/ops/causal_softmax/ascend/causal_softmax_aclnn.cc
> +    int64_t total_seq_len = static_cast<int64_t>(shape[ndim - 1]);
加了

2024-10-18 02:06 UTC, kilinchange commented
![image](https://github.com/user-attachments/assets/6b5f10c0-c6df-4673-ba93-249ee9f0d2fa)
nv 平台测试通过

2024-10-18 02:25 UTC, zhangyue207 commented
![image](https://github.com/user-attachments/assets/29c91065-d9d3-46d9-bbaa-c75b8df6cbac)

2024-10-18 02:31 UTC, kilinchange approved these changes

2024-10-18 03:46 UTC, PanZezhong1725 approved these changes

2024-10-18 03:46 UTC, merged