Ascend matmul
PanZezhong1725/operators pull request #83
Opened 2024-10-18 04:19 UTC by zhangyue207

昇腾matmul

2024-10-18 04:23 UTC, zhangyue207 commented
![image](https://github.com/user-attachments/assets/c1e44a14-705f-43de-b6e3-f400ba7ccc87)
结果验证

2024-10-21 08:59 UTC, PanZezhong1725 requested changes

2024-10-21 08:59 UTC, PanZezhong1725 commented on src/ops/matmul/ascend/matmul_aclnn.cc
> +    if (c_desc->ndim != 2 || a_desc->ndim != 2 || b_desc->ndim != 2) {
需要支持batch的情况，([batch, ] m, n)

2024-10-24 06:34 UTC, xgqdut2016 commented on src/ops/matmul/ascend/matmul_aclnn.cc
> +    status = bDesc->createTensor();
如果判断c_desc的时候status=failed，但是最后判断bDesc的时候status=success，程序如何处理这种问题呢？这里感觉需要加一个规则，一旦发现status失败，马上跳出程序，这样才方便后面检查代码的问题

2024-10-24 06:58 UTC, xgqdut2016 commented on src/ops/matmul/ascend/matmul_aclnn.cc
> +
这里是不是需要delete desc

2024-10-24 07:01 UTC, xgqdut2016 commented on src/ops/matmul/ascend/matmul_aclnn.cc
> +
这里传入的c,a,b的数据类型本来就是void *，为什么这个地方又做了一次(void *)a强制转换，是不是写错了，得是(half *)a？

2024-10-30 07:32 UTC, zhangyue207 commented on src/ops/matmul/ascend/matmul_aclnn.cc
> +
已加

2024-10-30 07:33 UTC, zhangyue207 commented on src/ops/matmul/ascend/matmul_aclnn.cc
> +
参数规定的是 void const* 但是 acl接口规定的是 void * ， void const * 和 void * 不是匹配的数据类型

2024-10-30 07:36 UTC, zhangyue207 commented
![image](https://github.com/user-attachments/assets/ea2646b7-db98-4777-a136-d0ab684e44ca)

2024-10-30 07:54 UTC, PanZezhong1725 requested changes

2024-10-30 07:54 UTC, PanZezhong1725 commented on src/ops/matmul/ascend/matmul_aclnn.cc
> +        CHECK_RET(ret == ACL_SUCCESS,
出错应该返回错误status。把用这个宏的地方补一下

2024-10-30 08:08 UTC, zhangyue207 commented on src/ops/matmul/ascend/matmul_aclnn.cc
> +        CHECK_RET(ret == ACL_SUCCESS,
fixed

2024-10-30 08:27 UTC, PanZezhong1725 approved these changes

2024-10-30 08:42 UTC, merged