Ascend rearrange
PanZezhong1725/operators pull request #84
Opened 2024-10-18 06:31 UTC by zhangyue207

2024-10-18 06:32 UTC, zhangyue207 commented
![image](https://github.com/user-attachments/assets/03f1933d-88c8-4a4d-a680-6d34227fb6cb)

2024-10-21 09:02 UTC, PanZezhong1725 requested changes

2024-10-21 09:02 UTC, PanZezhong1725 commented on src/ops/matmul/ascend/matmul_aclnn.cc
> +#include "matmul_aclnn.h"
这些应该是matmul的更改？和rearrange分开吧

2024-10-24 07:05 UTC, xgqdut2016 commented on src/ops/rearrange/ascend/rearrange_aclnn.cc
> +    AclSetTensorAddr(executor, 1, ts, (void *) src);
本来传入的src就是void *，为什么这里又要做一次(void *)src

2024-10-30 09:13 UTC, zhangyue207 commented
![image](https://github.com/user-attachments/assets/fcb443e5-6771-4084-bb62-d50ac300bacf)

2024-11-01 06:54 UTC, PanZezhong1725 approved these changes

2024-11-01 06:54 UTC, merged