Ascend rms norm
PanZezhong1725/operators pull request #85
Opened 2024-10-18 07:18 UTC by zhangyue207

![image](https://github.com/user-attachments/assets/77b8bbdf-4ddd-45b8-bf1d-3f58050e9d01)

2024-10-24 06:16 UTC, xgqdut2016 commented on src/ops/matmul/ascend/matmul_aclnn.cc
> +    status = aDesc->fromInfiniOpTensorDescriptor(a_desc);
这个地方，如果判断c_desc的时候返回的status是failed，但是后面判断a_desc以及其他的时候status是success，运行过程中会报错么？这里是不是干脆指定，如果有一个status出错，直接跳出程序

2024-10-24 06:19 UTC, zhangyue207 commented on src/ops/matmul/ascend/matmul_aclnn.cc
> +    status = aDesc->fromInfiniOpTensorDescriptor(a_desc);
这里确实，需要对每次status 返回值check 一下

2024-10-24 07:51 UTC, xgqdut2016 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +
需要delete desc?

2024-11-01 06:56 UTC, zhangyue207 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +
这个问题是ascend 接口要求接受的数据类型是double，我们给的是float，这个结构体的作用就是构建ascend 接口的参数

2024-11-01 07:02 UTC, zhangyue207 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +                              void *w,
这个等cuda那边一起改吧或者单独提PR

2024-11-01 07:02 UTC, zhangyue207 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +
DONE

2024-11-01 08:30 UTC, PanZezhong1725 requested changes

2024-11-01 08:30 UTC, PanZezhong1725 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +        auto ret = aclnnCastGetWorkspaceSize(tw, castDesc->dataType, tcast, &workspaceSize, &castExecutor);
cast相关的这些不能放到建descriptor那步里吗

2024-11-01 08:30 UTC, PanZezhong1725 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +    auto &handle = desc->handle;
如果只是为了拿deviceid没必要存handle

2024-11-01 08:30 UTC, PanZezhong1725 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +    handle = nullptr;
不要存handle，以及任何外部用户的管理的数据。如果之前已经合并的算子也有这种情况的话，请一并修改

2024-11-01 08:36 UTC, zhangyue207 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +    handle = nullptr;
会有什么问题么

2024-11-01 08:38 UTC, zhangyue207 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +        auto ret = aclnnCastGetWorkspaceSize(tw, castDesc->dataType, tcast, &workspaceSize, &castExecutor);
不好放

2024-11-01 08:40 UTC, zhangyue207 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +    handle = nullptr;
ok，那我先在这个pr里改，其他已经合并的后面单独提PR改

2024-11-04 03:49 UTC, PanZezhong1725 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +        (*rstd_strides)[i] = (*rstd_strides)[i + 1] * (*rstd_shape)[i + 1];
为什么rstd_strides要根据连续的shape创建，是不支持非连续吗？

2024-11-04 05:43 UTC, zhangyue207 commented on src/ops/rms_norm/ascend/rms_norm_aclnn.cc
> +        (*rstd_strides)[i] = (*rstd_strides)[i + 1] * (*rstd_shape)[i + 1];
rstd 这个tensor 是自己传进去的，计算结果的输出之一，不传不行。连不连续无所谓，我们接口又没有这个

2024-11-04 06:34 UTC, PanZezhong1725 approved these changes

2024-11-04 07:20 UTC, kilinchange approved these changes

2024-11-04 07:22 UTC, merged