fp16 and fp32 support for global avg pool (initial commit)
PanZezhong1725/operators pull request #89
Opened 2024-10-28 03:37 UTC by Ziminli

2024-11-01 04:13 UTC, kilinchange requested changes

2024-11-05 02:49 UTC, Ziminli commented on src/ops/global_avg_pool/cuda/global_avg_pool.cu
> +void launch_global_avg_pool_folding(GlobalAvgPoolCudaDescriptor_t desc, void *y, void const *x, void *workspace, uint64_t workspace_size, void *stream, unsigned pack_size) {
是的，这里是根据是否有workspace进行优化，因为workspace根据不同的数据类型会有所变化，比如fp32和fp64这种情况下其实是不需要workspace的，这时候就不用调用有workspace的版本。如果像fp16需要workspace的话就会自动调用有workspace的版本。

2024-11-06 08:29 UTC, PanZezhong1725 approved these changes

2024-11-06 08:34 UTC, kilinchange approved these changes

2024-11-06 08:39 UTC, PanZezhong1725 approved these changes

2024-11-06 08:46 UTC, merged