Ascend Swiglu
PanZezhong1725/operators pull request #90
Opened 2024-10-30 08:28 UTC by zhangyue207

![image](https://github.com/user-attachments/assets/e1901ef8-f946-4209-9d39-cd919af7d4e4)

2024-11-04 08:37 UTC, zhangyue207 commented
![image](https://github.com/user-attachments/assets/2d697473-cdf3-4e2b-bbc2-aa9a95f77182)

2024-11-04 09:01 UTC, xgqdut2016 commented on src/ops/swiglu/ascend/swiglu.cc
> +    return STATUS_SUCCESS;
为什么这里还需要额外(void *)a，b，上面传入的a,b不是已经是void *了吗

2024-11-05 02:51 UTC, zhangyue207 commented on src/ops/swiglu/ascend/swiglu_kernel.cpp
> +extern "C" void swiglu_kernel_do(void *c, void *a, void *b,
![image](https://github.com/user-attachments/assets/9b053b69-cc94-4832-9862-828129a907e5)
![image](https://github.com/user-attachments/assets/7de5336c-84aa-4ad6-892c-ce302f92729b)
void const * 与GM_ADDR 类型不兼容，所以kernel里边接口统一用void * 类型

2024-11-05 09:42 UTC, PanZezhong1725 requested changes

2024-11-05 09:42 UTC, PanZezhong1725 commented on src/ops/rotary_embedding/ascend/rotary_embedding.cc
> +    rope_kernel_do(t, (void *) pos_ids, (void *) sin_table, (void *) cos_table,
算子计算如果类型不支持要返回错误，可以让这个方法也返回status

2024-11-05 09:42 UTC, PanZezhong1725 commented on src/ops/swiglu/ascend/swiglu.cc
> +    swiglu_kernel_do(c, (void *) a, (void *) b, 1.0, seq_len, di, sta, stb, stc, dt, stream);
判断类型是否支持，不支持返回错误

2024-11-05 09:44 UTC, PanZezhong1725 requested changes

2024-11-05 09:44 UTC, PanZezhong1725 commented on xmake.lua
> +        add_links("libswiglu.so")
这里有没有什么更好的方法？我们install operators会把编好的动态库和header复制到一个目录下，如果这里依赖动态库，那这些动态库也需要被复制过去。需要讨论一下

2024-11-12 05:59 UTC, PanZezhong1725 approved these changes

2024-11-12 06:39 UTC, kilinchange requested changes

2024-11-12 06:39 UTC, kilinchange commented on operatorspy/tests/rotary_embedding.py
> +    t_out = torch.view_as_real(t_ * freqs_cis).flatten(2).to(t.dtype)
这里可以调原来的 rotary_embedding 函数吧，torch_device 传 “cpu” 就行，拿到返回的函数结果后 to npu 就行

2024-11-12 06:44 UTC, xgqdut2016 approved these changes

2024-11-13 06:20 UTC, kilinchange approved these changes

2024-11-13 07:33 UTC, merged