Add gemm
PanZezhong1725/operators pull request #93
Opened 2024-10-31 07:40 UTC by Ziminli

- Add GEMM operator
 - Add Expand operator
 - Add FP32 support for matmul operator
 - Misc. changes to common utilities

2024-11-01 07:47 UTC, kilinchange requested changes

2024-11-01 07:47 UTC, kilinchange commented on src/devices/cpu/common_cpu.cc
> +uint64_t getNextIndex(uint64_t flat_index, uint64_t ndim, uint64_t const *shape, int64_t const *strides) {
改下名称，内存布局的偏移统一叫 offset，shape 层面的偏移统一叫 index 吧

2024-11-01 07:47 UTC, kilinchange commented on src/ops/expand/cpu/expand_cpu.h
> +typedef struct ExpandCpuDescriptor *ExpandCpuDescriptor_t;
对外暴露的类型名统一要加前缀 infiniop，所以这里用 infiniopExpandCpuDescriptor_t 吧

2024-11-01 07:47 UTC, kilinchange commented on src/ops/expand/cuda/expand.cc
> +    checkCudaErrorWithCode(cudaMalloc(&y_shape_d, ndim * sizeof(uint64_t)), STATUS_MEMORY_NOT_ALLOCATED);
改成一次分配然后算 offset 给指针赋值吧

2024-11-01 07:47 UTC, kilinchange commented on src/ops/expand/cuda/expand.cuh
> +typedef struct ExpandCudaDescriptor *ExpandCudaDescriptor_t;
加 infiniop 前缀

2024-11-01 07:51 UTC, Ziminli commented on operatorspy/tests/expand.py
> +        # ((32, 150, 51200), (32, 150, 1), None, None),
因为GitHub CI 用CPU跑会比较慢，主要是用来测较大数据规模时性能的，如果不需要可以删掉

2024-11-01 08:15 UTC, kilinchange requested changes

2024-11-01 08:15 UTC, kilinchange commented on src/ops/matmul/cuda/matmul_cuda.cu
> +        compute_type = CUBLAS_COMPUTE_32F_FAST_16F;
这个会把 fp32 转成 fp16 计算，精度会不会出问题，建议用 CUBLAS_COMPUTE_32F_FAST_TF32 使用 tf32 算

2024-11-01 08:15 UTC, kilinchange commented on src/ops/matmul/cuda/matmul_cuda.cu
> +}
结尾加空行

2024-11-05 02:20 UTC, Ziminli commented on operatorspy/tests/expand.py
> +        # ((32, 150, 51200), (32, 150, 1), None, None),
已删除

2024-11-06 02:24 UTC, kilinchange approved these changes

2024-11-06 08:13 UTC, PanZezhong1725 approved these changes

2024-11-06 08:15 UTC, PanZezhong1725 requested changes

2024-11-06 08:15 UTC, PanZezhong1725 commented on src/ops/expand/cuda/expand.cc
> +    cudaFree((void *) desc->strides_and_shape_d);
cuda方法调用检查一下结果

2024-11-06 08:35 UTC, PanZezhong1725 approved these changes

2024-11-06 08:35 UTC, merged